return {
	mod_description = {
		en = "Shows your current customization for given career in hero select screen.",
		fr = "Affiche votre personnalisation actuelle pour une carrière donnée dans l'écran de sélection des héros.",
		de = "Zeigt deine aktuelle Anpassung für eine bestimmte Karriere auf dem Heldenauswahlbildschirm an.",
		es = "Muestra su personalización actual para una carrera determinada en la pantalla de selección de héroe.",
		ru = "Показывает вашу текущую настройку для данной карьеры на экране выбора героев.",
		it = "Mostra la tua personalizzazione attuale per una determinata carriera nella schermata di selezione dell'eroe.",
		pl = "Pokazuje aktualnie wybraną personalizację postaci na bohaterze w menu wyboru postaci.",
		["br-pt"] = "Mostra sua personalização atual para determinada carreira na tela de seleção do herói.",		
	},
	classic_anims = {
		en = "Classic animations",
		fr = "Animations classiques",
		de = "Klassische animationen",
		es = "Animaciones clásicas",
		ru = "Классическая анимация",
		it = "Animazioni classiche",
		pl = "Klasyczne animacje",
		["br-pt"] = "Animações clássicas",		
	},
	classic_anims_description = {
		en = "Changes animation of some classes to Vermintide 1 variants.",
		fr = "Change l'animation de certaines classes en variantes Vermintide 1.",
		de = "Ändert die Animation einiger Klassen in Vermintide 1-Varianten.",
		es = "Cambia la animación de algunas clases a las variantes de Vermintide 1.",
		ru = "Изменяет анимацию некоторых классов на Vermintide 1 вариант.",
		it = "Cambia l'animazione di alcune classi nelle varianti di Vermintide 1.",
		pl = "Zmienia animacje niektórych klas na klasyczne warianty z Vermintide 1.",
		["br-pt"] = "Altera a animação de algumas classes para as variantes do Vermintide 1.",		
	},
	background_objects = {
		en = "Background objects",
		fr = "Objets de fond",
		de = "Hintergrundobjekte",
		es = "Objetos de fondo",
		ru = "Фоновые объекты",
		it = "Oggetti di sfondo",
		pl = "Obiekty w tle",
		["br-pt"] = "Objetos de fundo",		
	},
	background_objects_description = {
		en = "Objects that will be displayed in background of hero share menu.",
		fr = "Objets qui seront affichés en arrière-plan du menu de partage du héros.",
		de = "Objekte, die im Hintergrund des Heldenfreigabemenüs angezeigt werden.",
		es = "Objetos que se mostrarán en el fondo del menú de compartir héroe.",
		ru = "Объекты, которые будут отображаться в фоновом режиме меню общих героев.",
		it = "Oggetti che verranno visualizzati sullo sfondo del menu di condivisione dell'eroe.",
		pl = "Obiekty, które będą wyświetlane w tle menu podglądu bohatera.",
		["br-pt"] = "Objetos que serão exibidos no plano de fundo do menu de compartilhamento de herói.",		
	},	
	background_none = {
		en = "None",
		fr = "Aucun",
		de = "Keiner",
		es = "Ninguna",
		ru = "Никто",
		it = "Nessuna",
		pl = "Brak",
		["br-pt"] = "Nenhum",		
	},
	background_waystone = {
		en = "1",
		fr = "1",
		de = "1",
		es = "1",
		ru = "1",
		it = "1",
		pl = "1",
		["br-pt"] = "1",		
	},
	background_map = {
		en = "2",
		fr = "2",
		de = "2",
		es = "2",
		ru = "2",
		it = "2",
		pl = "2",
		["br-pt"] = "2",		
	},
	background_deed = {
		en = "3",
		fr = "3",
		de = "3",
		es = "3",
		ru = "3",
		it = "3",
		pl = "3",
		["br-pt"] = "3",		
	},
	background_equipment = {
		en = "4",
		fr = "4",
		de = "4",
		es = "4",
		ru = "4",
		it = "4",
		pl = "4",
		["br-pt"] = "4",		
	},
	background_talents = {
		en = "5",
		fr = "5",
		de = "5",
		es = "5",
		ru = "5",
		it = "5",
		pl = "5",
		["br-pt"] = "5",		
	},
	background_forge = {
		en = "6",
		fr = "6",
		de = "6",
		es = "6",
		ru = "6",
		it = "6",
		pl = "6",
		["br-pt"] = "6",		
	},
	background_cosmetics = {
		en = "7",
		fr = "7",
		de = "7",
		es = "7",
		ru = "7",
		it = "7",
		pl = "7",
		["br-pt"] = "7",		
	},
	background_system = {
		en = "8",
		fr = "8",
		de = "8",
		es = "8",
		ru = "8",
		it = "8",
		pl = "8",
		["br-pt"] = "8",		
	},	
}